version: '3.5'
services:
    elastic:
        build:
            context: ./elastic
        volumes:
            - esdata:/usr/share/elasticsearch/data,rw
        restart: unless-stopped
    fuseki:
        build:
            context: ./fuseki
        volumes:
            - ./data/:/staging
            - fuseki-db:/fuseki-base/databases
    api:
        build:
            context: ./node
        environment:
            - NEWS_READER_SPARQL_ENDPOINT=http://fuseki:3030/ds/sparql
            - NEWS_READER_TEXT_INDEX_SEARCH=http://elastic:9200/ylenews/_search
        ports:
            - 3003:8080
        restart: unless-stopped
    client:
        build:
            context: ./client
        ports:
            - 5002:3000
    tasks:
        build:
            context: ./node
            dockerfile: Dockerfile.tasks
        environment:
            - NEWS_READER_SPARQL_ENDPOINT=http://fuseki:3030/ds/sparql
            - NEWS_READER_TEXT_INDEX=http://elastic:9200/ylenews
            - WIKIDATA_URI_CHUNK_SIZE=100
            - NODE_OPTIONS=--max-old-space-size=4096
        volumes:
            - ./yledata/:/app/yledata
            - ./data/:/app/data
volumes:
    fuseki-db:
    esdata:
