FROM node:alpine

COPY package* /

WORKDIR /

RUN npm install

WORKDIR /app/


COPY src/tasks/* /app/
COPY src/config.js /
COPY src/api/lib/* /api/lib/

RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
